/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package template

import com.kotlindiscord.kord.extensions.ExtensibleBot
import com.kotlindiscord.kord.extensions.checks.anyGuild
import dev.kord.common.entity.Snowflake
import template.extensions.FunExtension
import template.extensions.ModerationExtension

suspend fun main() {

    val bot = ExtensibleBot(System.getenv("DISCORD_TOKEN")) {
        chatCommands {
            enabled = true

            check {
                anyGuild()
            }

            prefix {
                "!"
            }
        }

        extensions {
            add(::ModerationExtension)
            add(::FunExtension)
        }
    }

    bot.start()
}
